// This file was generated by package:dart_define, DO NOT modify or remove these comments
class DartDefine {
  DartDefine._();
  
  /// The flavor the app was launched with
  static Flavor get flavor => FlavorExtension.fromString(
        const String.fromEnvironment('FLAVOR'),
      );

  /// appId
  static const appid = String.fromEnvironment('appId');

  /// appIdSuffix
  static const appidsuffix = String.fromEnvironment('appIdSuffix');

  /// key1
  static const key1 = String.fromEnvironment('key1');

  /// key2
  static const key2 = String.fromEnvironment('key2');

}

/// The flavors supported by the application
enum Flavor {
  /// Production environment
  prod,
  
  /// Staging environment
  stg,
  
  /// Development environment
  dev,
  
}

extension FlavorExtension on Flavor {
  static Flavor fromString(String value) {
    switch (value) {
      case 'prod':
        return Flavor.prod;
      case 'stg':
        return Flavor.stg;
      case 'dev':
        return Flavor.dev;
      default:
        throw throw Exception('Invalid flavor');
    }
  }
}

    