// This file was generated by package:dart_define, DO NOT modify or remove these comments
class DartDefine {
  DartDefine._();
  
  /// Key1
  static const key1 = String.fromEnvironment('KEY1');

  /// Key2
  static const key2 = String.fromEnvironment('KEY2');
}

    